Refactor, use latest YunoHost 2.7.2 standards

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -1,38 +1,86 @@
 #!/bin/bash
 
-# Exit on command errors and treat unset variables as an error
-set -eu
+#=================================================
+# GENERIC START
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
 
-shopt -s extglob  # sets extended pattern matching options in the bash shell
+source _common.sh
+source /usr/share/yunohost/helpers
+
+#=================================================
+# LOAD SETTINGS
+#=================================================
 
 app=$YNH_APP_INSTANCE_NAME
 
-# Source local helpers
-source ./_common.sh
-SRCPATH=$(pwd)
+domain=$(ynh_app_setting_get $app domain)
+path_url=$(ynh_app_setting_get $app path)
+is_public=$(ynh_app_setting_get $app is_public)
 
-# Source YunoHost helpers
-source /usr/share/yunohost/helpers
 
-# Retrieve app settings
-domain=$(ynh_app_setting_get "$app" domain)
-path=$(ynh_app_setting_get "$app" path)
-is_public=$(ynh_app_setting_get "$app" is_public)
+#=================================================
+# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
+#=================================================
 
-# Fix path if needed
-path=$(fix_path $path)
+ynh_backup_before_upgrade	# Backup the current version of the app
+ynh_clean_setup () {
+	ynh_restore_upgradebackup	# restore it if the upgrade fails
+}
+ynh_abort_if_errors	# Active trap pour arrêter le script si une erreur est détectée.
 
-# Upgrade dependencies
-ynh_package_install_from_equivs ../conf/${DEPS_PKG_NAME}.control \
-|| ynh_die "Unable to upgrade dependencies"
+#=================================================
+# CHECK THE PATH
+#=================================================
 
-# Download and extract application 
-NETDATA_TMPDIR=$(extract_application)
+# Normalize the URL path syntax
+path_url=$(ynh_normalize_url_path $path_url)
+
+#=================================================
+# STANDARD UPGRADE STEPS
+#=================================================
+#=================================================
+# NGINX CONFIGURATION
+#=================================================
+
+nginx_conf="../conf/nginx.conf"
+if [ "$path_url" = "/" ]
+then
+  # Handle root path, avoid double slash.
+  # Temporary fix, in waiting for an upgrade of the helper. (#361)
+  path_url_slash_less=${path_url%/}
+  ynh_replace_string "__PATH__/" "$path_url_slash_less/" $nginx_conf
+else
+  # Move prefix comment #for-subdir at end of lines
+  ynh_replace_string "#for-subdir\(.*\)" "\1 #for-subdir" $nginx_conf
+fi  
+
+# Create a dedicated nginx config
+ynh_add_nginx_config
+
+#=================================================
+# UPGRADE DEPENDENCIES
+#=================================================
+
+ynh_install_app_dependencies $pkg_dependencies
+
+#=================================================
+# DOWNLOAD, CHECK AND UNPACK SOURCE
+#=================================================
+
+# Download, check integrity, uncompress and patch the source from app.src
+NETDATA_TMPDIR=$(mktemp -d)
+ynh_setup_source "$NETDATA_TMPDIR"
+
+#=================================================
+# SPECIFIC UPGRADE
+#=================================================
 
 # signal netdata to start saving its database
 # this is handy if your database is big
 pids=$(pidof netdata)
-[ ! -z "${pids}" ] && sudo kill -USR1 ${pids}
+[ ! -z "${pids}" ] && kill -USR1 ${pids}
 
 # create a temporary file for the log
 tmp=$(mktemp /tmp/netdata-updater-log-XXXXXX.log)
@@ -40,53 +88,29 @@ tmp=$(mktemp /tmp/netdata-updater-log-XXXXXX.log)
 exec 3>${tmp}
     
 # Launch netdata installation in /opt directory
-cd $NETDATA_TMPDIR
-sudo ./netdata-installer.sh --install /opt --dont-wait >&3 2>&3 || ynh_die "FAILED TO COMPILE/INSTALL NETDATA"
+pushd $NETDATA_TMPDIR
+./netdata-installer.sh --install /opt --dont-wait >&3 2>&3 || ynh_die "FAILED TO COMPILE/INSTALL NETDATA"
 
-# Create netdata user to monitor MySQL (if needed)
-is_mysql_user_existing=$(ynh_mysql_execute_as_root "select user from mysql.user where user = 'netdata';")
-if [ -z "$is_mysql_user_existing" ] ; then
-  ynh_mysql_execute_as_root "create user 'netdata'@'localhost';
-  grant usage on *.* to 'netdata'@'localhost' with grant option;
-  flush privileges;"
-fi
+configure_netdata
 
-# Give dovecot privileges to netdata user to monitor Dovecot
-# Need dovecot 2.2.16+
-sudo setfacl -m u:netdata:rw /var/run/dovecot/stats
+# Store the app.src file
+popd
+cp ../conf/app.src /opt/netdata/etc/netdata
 
-# Add netdata to the adm group to access web logs
-sudo usermod -a -G adm netdata
-
-# Extend weblog path to process logs for every domain
-sed -i "s@path: '/var/log/nginx/access.log'@path: '/var/log/nginx/*-access.log'@g" /opt/netdata/etc/netdata/python.d/web_log.conf
-
-# Declare service for YunoHost monitoring
-sudo yunohost service add netdata --log "/opt/netdata/var/log/netdata/error.log" "/opt/netdata/var/log/netdata/access.log" "/opt/netdata/var/log/netdata/debug.log"
-
-# Restart NetData
-sudo systemctl restart netdata
-
-# Store the uninstaller for the removal script
-sudo mv ./netdata-uninstaller.sh /opt/netdata/etc/netdata
-# Store the local helper for backup/restore scripts
-sudo cp $SRCPATH/_common.sh /opt/netdata/etc/netdata
-
-# Modify Nginx configuration file and copy it to Nginx conf directory
-if [[ "$path" == "/" ]] ; then
-  nginx_conf=$SRCPATH/../conf/nginx_root.conf
-else
-  nginx_conf=$SRCPATH/../conf/nginx_sub_dir.conf
-fi
-
-sed -i "s@YNH_WWW_PATH@${path}@g" $nginx_conf
-sudo cp $nginx_conf /etc/nginx/conf.d/$domain.d/$app.conf
-
+#=================================================
+# GENERIC FINALIZATION
+#=================================================
+# SETUP SSOWAT
+#=================================================
 # If app is public, add url to SSOWat conf as skipped_uris
 if [[ $is_public -eq 1 ]]; then
   # See install script
   ynh_app_setting_set "$app" unprotected_uris "/"
 fi
 
-# Reload nginx service
-sudo systemctl reload nginx
+#=================================================
+# RELOAD NGINX
+#=================================================
+
+systemctl reload nginx
+
